- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJS
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs

    - name: Copy Backend Service File
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Add Application User
      ansible.builtin.user:
        name: expense

    - name: Clean App Content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create App Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download Frontend Code and Extract it
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Install NodeJS Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app


    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
    - name: Load Schema
      ansible.builtin.shell: ysql -h mysql.rdevopsb73.online -uroot -p$mysql_root_password < /app/schema/backend.sql

    - name: Start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes





#source common.sh
#component=backend
#
#type npm &>>$log_file
#if [ $? -ne 0 ]; then
#echo Install NodeJS Repos
#curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>$log_file
#stat_check
#
#echo Install NodeJS22
#dnf install nodejs -y &>>$log_file
#stat_check
#fi
#
#echo Copy Backend Service File
#cp backend.service /etc/systemd/system/backend.service &>>$log_file
#stat_check
#
#echo Add Application User
#id expense &>>$log_file
#if [ $? -ne 0 ]; then
#useradd expense &>>$log_file
#fi
#stat_check
#
#echo Clean App Content
#rm -rf /app &>>$log_file
#stat_check
#
#mkdir /app
#cd /app
#
#download_and_extract
#
#echo Download Dependencies
#npm install &>>$log_file
#stat_check
#
#echo Start Backend Service
#systemctl daemon-reload &>>$log_file
#systemctl enable backend &>>$log_file
#systemctl restart backend &>>$log_file
#stat_check
#
#echo Install MySQL Client
#dnf install mysql -y &>>$log_file
#stat_check
#
#echo Load Schema
#mysql_root_password=$1
#mysql -h mysql.rdevopsb73.online -uroot -p$mysql_root_password < /app/schema/backend.sql &>>$log_file
#stat_check


