- name: MySQL Setup
  hosts: all
  become: yes
  tasks:
    - name: Copy MySQL Repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    ## Cross check
    - name: Disbale MySQL 8 Version
      ansible.builtin.shell: dnf module disable mysql -y

    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Start MySQL
      ansible.builtin.systemd:
        name: mysqld
        state: restarted

    - name: Set Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1